### PR TITLE
WiP: Coverage/metadata encoding

### PR DESCRIPTION
**Pull request by constantinius**
Work in progress! Will be discussed on the hackathon.

This PR adds information about how to encode coverages and/or parts thereof. 

For a complete coverage, the use of `multipart/related` with `rangetype=...` etc. parameters added.

For the rangeset only it details the usage of parameters for GeoTIFF encoding taken from the GeoTIFF encoding specification.

### CODE REVIEW

**Comment by Schpidi** [comment]
20200923: Coverages SWG call: Document this in the Users Guide rather than the specification itself.

**Comment by Schpidi** [comment]
in support of the PR https://www.w3.org/Protocols/rfc1341/4_Content-Type.html

**Comment by Schpidi** [comment]
maybe we need to use the `;q=` parameter to define `accept-params` as defined in RFC7231 https://tools.ietf.org/html/rfc7231#section-5.3

**Comment by Schpidi** [comment]
related to https://github.com/opengeospatial/ogcapi-common/issues/8

**Comment by Schpidi** [comment]
monitor the proposal for "Content Negotiation by Profile" https://www.w3.org/TR/dx-prof-conneg/

**Comment by KathiSchleidt** [comment]
As related to conneg by profile, latest news seems to be at: https://github.com/opengeospatial/ogcapi-common/issues/8#issuecomment-814917551

**Comment by jerstlouis** [comment]
Closing this PR as it is 5 years, with no activity in the last 3 years, and it is obsoleted by events.

In general, rather than using `multipart/related`, the recommendation is to use self-contained coverage encodings with the API.  Metadata such as ISO19115 can also be linked from the coverage's collection description using the link relation `http://www.opengis.net/def/rel/ogc/1.0/data-meta` as described in [Common - Part 2](https://docs.ogc.org/DRAFTS/20-024.html#link-relations-section). Basic information such as the description of the dimensions is directly included at `/collections/{collectionId}` in the collection description, and the description of the fields (range type) is available as a (logical) JSON Schema at `/collections/{collectionId}/schema`.

Please open a new issue and/or join the Coverages SWG meeting at 10:00 AM Eastern on Wednesdays for any discussion  related to this PR.

**Pull request closed without merging**
